### ISSUE TITLE
Typo in error code 403 from DELETE /users/me/spotify

### ISSUE THREAD

**Issue by IvanVegaM** [TofuDotTech/CrujofestApiDocs#12]
<img width="1422" alt="Screenshot 2023-12-08 at 2 47 38 p m" src="https://github.com/TofuDotTech/CrujofestApiDocs/assets/88522583/1a35f596-08ac-43c8-b47b-0a292cdf71a7">

Instead of errror_logout is error_logout, as an example of an error response from the api:

<img width="1283" alt="Screenshot 2023-12-08 at 2 49 09 p m" src="https://github.com/TofuDotTech/CrujofestApiDocs/assets/88522583/66cc91b3-4def-443b-a18b-30be0fc01dce">

**Comment by CarlosLecval** [comment]
fixed
